 
 /*------------------------------------------------------------------------
    File        : keleivioBusena
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : Studentas
    Created     : Wed Jul 11 15:03:09 EEST 2018
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

block-level on error undo, throw.

enum uzduotis11.keleivioBusena: 
    define enum lifte
                laukia
                pastate.
end enum.