 
 /*------------------------------------------------------------------------
    File        : liftoBusena
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : Studentas
    Created     : Wed Jul 11 15:03:17 EEST 2018
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

block-level on error undo, throw.

enum uzduotis11.liftoBusena: 
    define enum uzimtas
                laisvas.
end enum.