 
 /*------------------------------------------------------------------------
    File        : Lift_state
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : Studentas
    Created     : Wed Jul 11 15:40:27 EEST 2018
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

BLOCK-LEVEL ON ERROR UNDO, THROW.

ENUM enum.Lift_state: 
    DEFINE ENUM laisvas
                uzimtas.
END ENUM.