 
 /*------------------------------------------------------------------------
    File        : duruBusena
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : Studentas
    Created     : Wed Jul 11 14:04:20 EEST 2018
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

block-level on error undo, throw.

enum src.duruBusena: 
    define enum atidarytos
                uzdarytos.
end enum.