 
 /*------------------------------------------------------------------------
    File        : keleivioBusena
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : Studentas
    Created     : Wed Jul 11 14:55:47 EEST 2018
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

block-level on error undo, throw.

enum src.keleivioBusena: 
    define enum lifte
                vaziuoja
                pastate.
end enum.