 
 /*------------------------------------------------------------------------
    File        : liftoBusena
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : Studentas
    Created     : Wed Jul 11 13:56:13 EEST 2018
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

block-level on error undo, throw.

enum src.liftoBusena: 
    define enum naudojamas
                laisvas.
end enum.